services:
  - type: web
    name: booking-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      # Add your variables as needed, e.g. DATABASE_URL, CORS_ORIGINS, etc.

